  services:
    app-service:
      build:
        context: ./app-service # specify directory where local Dockerfile is located
    auth-service:
      build:
        context: ./auth-service # specify directory where local Dockerfile is located
    nginx:
      volumes:
        - /root/nginx.conf:/etc/nginx/nginx.conf:ro