[http]
address = "0.0.0.0:3000"
jwt_token = ""
jwt_cookie_name = "jwt"

[grpc]
address = "0.0.0.0:50051"

[database]
url = "postgres://postgres:${POSTGRES_PASSWORD}@localhost:5432"

[redis]
host_name = "127.0.0.1"
ttl_millis = 600000

[email]
base_url = "https://api.postmarkapp.com/email"
sender = "bogdan@codeiron.io"
timeout_milliseconds = 10000